console_url=http://localhost:8081/
console_api_key=
console_cli_path=C:\CAST\com.castsoftware.aip.console.tools.2.11.12-funcrel\aip-console-tools-cli.jar

max_batches=2
applications_file=C:\work\servtool_248_LM_Automate_AIP_Onboarding_Process\CASTAIPAutomation\CASTAIPAutomation\applications.txt
source_code_path=C:\work\servtool_248_LM_Automate_AIP_Onboarding_Process\CASTAIPAutomation\source_code

output_csv_file_path=C:\work\servtool_248_LM_Automate_AIP_Onboarding_Process\CASTAIPAutomation\output_files
output_txt_file_path=C:\work\servtool_248_LM_Automate_AIP_Onboarding_Process\CASTAIPAutomation\output_files
output_log_file_path=C:\work\servtool_248_LM_Automate_AIP_Onboarding_Process\CASTAIPAutomation\output_files
 
# Step 2 - PostgreSQL and domain settings
domain_name=OCAS
pg_host=localhost
pg_port=
pg_database=postgres
pg_user=operator
pg_password=
output_excel_file_path=C:\work\servtool_248_LM_Automate_AIP_Onboarding_Process\CASTAIPAutomation\output_files

# Step 3 - Neo4j settings
neo4j_uri=bolt://localhost:7687
neo4j_username=neo4j
neo4j_password=
neo4j_database=

TargetApplicationList = ['Database']
